### ISSUE TITLE
PC doesn´t wake up

### ISSUE THREAD

**Issue by Videothek** [szabodanika/wake-pc#5]
Hey,

first of all really cool that you published this project, i was swarching for something like this for long.

But unfortunately i have a problem when waking up the PC.

The page says it was started but somehow the PC doesn´t wake up.

I have tested WOL with other Apps and they work fine.

So any clue why it isn´t working?

I have changed all the values for the first entry.

Is there anything special to note for the naming of the machines or so?

Thank you in advance :-)

**Comment by idunwannagotoschool** [comment]
https://github.com/szabodanika/wake-pc/pull/8#issue-1877767511

I am not sure if the maintainer will process the pull request but this commit should fix the issue.
